### PR TITLE
Multi module

### PR DESCRIPTION
**Pull request by peter-murray**
Adding multi module support and improving build processes of the action and cli executables.

### CODE REVIEW

**Comment by felickz** [comment]
Can [confirm](https://github.com/vulna-felickz/mvnexbook-examples-1.0/issues/1) i need to specify both `snapshot-include-file-name` and `snapshot-dependency-file-name` to get dependabot security alerts on the snapshot 👀

**Comment by peter-murray** [comment]
@felickz That does not seem right to me, but this is based on the underlying toolkit and the dependency tree itself does not change with those configuration values, so this would be related to the underlying JSON results being pushed up via the toolkit library.

Have you got some example POMs that I can build some tests against?

**Comment by felickz** [comment]
I would presume this is a bug in the API and not something you should be directly addressing.  I was using this [workflow](https://github.com/vulna-felickz/mvnexbook-examples-1.0/blob/8dcce39eb7f022b063003cae16cacb67840d9d77/.github/workflows/sbom-upload.yml#L33-L38) against a pretty [simple multi module sample ](https://github.com/vulna-felickz/mvnexbook-examples-1.0/tree/master/ch-multi)
```
    - name: Submit Web Dependency Snapshot
      uses: advanced-security/maven-dependency-submission-action@multi-module
      with:   
        directory: "./ch-multi/"
        snapshot-include-file-name: true
        snapshot-dependency-file-name: "./ch-multi/pom.xml"
```

**Comment by kimmoahokas** [comment]
Any estimates when this might be merged? Looks very good and we would like to take this to good use :)

**Comment by dominiquedejaeger-liantis** [comment]
Merging this features would be great for us because we are waiting for the mwnw support

**Comment by kimmoahokas** [comment]
@peter-murray Any information if this will be merged and available soon?

**Comment by peter-murray** [comment]
I am aiming to release this next week as I am still awaiting some feedback on an open use case before I release this as 3.0.

**Comment by felickz** [comment]
> @felickz That does not seem right to me, but this is based on the underlying toolkit and the dependency tree itself does not change with those configuration values, so this would be related to the underlying JSON results being pushed up via the toolkit library.
> 
> Have you got some example POMs that I can build some tests against?

FYI this behavior has been patched by product - all permutations of the `snapshot-include-file-name` and `snapshot-dependency-file-name` will generate Dependabot alerts when the snapshots contain vulnerable dependencies!

**Pull request merged**
